# Generated by Django 4.2 on 2023-05-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_first_name_userprofile_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
