# Generated by Django 4.2 on 2023-05-31 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
