# Generated by Django 4.2 on 2023-06-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('register', '0006_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUserAdmin',
            new_name='CustomUser',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
