# Generated by Django 4.2 on 2023-06-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_rename_customuseradmin_customuser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
