# Generated by Django 4.2 on 2023-06-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightSched', '0002_remove_bookingflight_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingflight',
            name='email',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
    ]
