# Generated by Django 4.2 on 2023-06-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightSched', '0003_bookingflight_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingflight',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
